### DISCUSSION TITLE
Docker installtion not working

### DISCUSSION THREAD

**Discussion by Hagenncl** [s-allius/tsun-gen3-proxy#231] [Q&A]
Hi Stefan, 

Ich bin sehr an deinem Projekt TSUN-Gen3-Proxy interessiert. 
Ich bestize ein TSUN TSOL-MS800. 

ich bin leider auf dem Themengebiet Dockers totaler Anfänger und scheitere bei deiner Anleitung der Proxy zu starten (docker build https://github.com/s-allius/tsun-gen3-proxy.git#main:app -t tsun-proxy) 

Ich habe im Home Assistant im Terminal den entsprechenden Befehl eingegeben und erhalte folgende Info: 
![Unbenannt](https://github.com/user-attachments/assets/1413fba8-9b27-4102-8426-376198cd1e76)

Entsprechend führen die weiteren Punkte ebenfalls nicht zum Erfolg. 

Kannst du mir sagen was ich falsch mache?

Danke dir
Beste Grüße

**Comment by s-allius** [comment]
Hallo FCBayern3,

es gibt mehrere Möglichkeiten, wie du den Proxy Starten kannst. Allerdings wird dies nicht im Terminal von Home Assistant (HA) gemacht.
Bisher gab es nur die Möglichkeit, den Proxy als Container auf Docker laufen zu lassen, dafür benötigt man einen Server, usw.

Mit der kommenden Version 0.12 wird es auch möglich sein, den Proxy direkt in HA als AddOn laufen zu lassen. Dies geht aber nur, wenn du `Home Assistant OS` oder `Supervised` benutzt. Wenn du diese Voraussetzung erfüllst, dann solltest du diesen Weg verfolgen. Derzeit gibt es aber noch keine Release. Die Release soll noch vor Weihnachten kommen. Ich würde dich da aber noch etwas vertrösten wollen, da wir den Installationsprozess gerade erst aufsetzen und noch nicht durch getestet haben.

Wenn du kein AddOn nutzen kannst, musst du einen kleinen Server mit Docker und Portainer aufsetzen. Ist für einen Anfänger aber schon nicht ganz einfach, wenn auch machbar.

Gruß Stefan

**Reply by Hagenncl** [reply]
Hi Stefan, 

Danke dir für dein Feedback :) 
Ah dann lag es daran , dass ich es immer in der Console / SSH im HA gestartet habe. 

Das freut mich dass es mit dem 0.12 dann möglich sein wird es aus HA zu starten und sogar noch vor Weihnachten erscheinen wird. 
Dann werde ich entsprechend warten bis ihr eine neue Version veröffentlicht. 

Grüße 
Nic

**Reply by s-allius** [reply]
Hallo Nic,

wenn du magst kannst du schonmal die Entwicklungsversion testen und uns Feedback geben.

Du kannst hier https://github.com/s-allius/tsun-gen3-proxy/tree/dev-0.12 starten. Im Dokument findest du ein Installations-Button um das Repository zu deiner HA installation hinzuzufügen. Danach kannst du dann das Add-On in der Entwicklerversion (dev) installieren und ausprobieren.

Wichtig du musst `HA OS` oder `HA supervisor`nutzen, ansonsten fehlt dir der notwendige Add-On support. Ausserdem musst du den Advanced Mode für AddOns einschalten, damit die Dev Version sehen kannst...

Ich hoffe ich habe nichts vergessen

**Reply by Hagenncl** [reply]
Hi Stefan vielen Dank für die Info. Habe mich heute direkt rangesetzt und die Installation des Addons hat funktioniert. 

Leider scheitere ich an der Konfiguration und das add-on bleibt bei folgedem Schritt in der Konsole hängen: 
![image](https://github.com/user-attachments/assets/ccfc3bd7-73b5-4f2b-a0d3-b833ef88bf66)

**Infos Hard- / Software:** 
TSOL-MS800
Model: RSW-1-10001
Firmware-Version: RSW_400_1_V3.29.148
DSP-Softwareversion: V5.1.09


**Folgende Schritte habe ich gemacht:**
1. Konfiguration des Addons mit meiner Seriennummer des Wechselrichters (ich habe einen GEN3 Wechselrichter)
2. DNS Freischaltung in der Fritz.Box für logger.talent-monitoring.com
3. DNS Freischaltung in AdGuard Addon: 
![image](https://github.com/user-attachments/assets/721875e0-8aca-4047-8cff-5d3435a02fec)


Habe ich etwas übersehen bzw. vergessen?

**Reply by s-allius** [reply]
Der Wechselrichter hohlt sich die neue IP-Adresse nur nach einem Neustart. Wenn du aus deinem Netz logger.talent-monitoring.com anpingst und dies zu deinem HA aufgelöst wird, ist alles richtig und es sollte spätestens morgen gehen.

**Reply by Hagenncl** [reply]
leider tut es das nicht. Was habe ich denn in den Einstellungen falsch gesetzt, dass er entsprechend nicht zum HA auflößt?
(mein HA hat die Adresse wie oben in dem Adguard Screenshot, beim Pingen kommt mir eine völlig unbekannte IP)

![image](https://github.com/user-attachments/assets/f86696d7-68a7-4cb1-ad31-7f19993b125c)

**Reply by s-allius** [reply]
Du must in deinem Router einen DNS Eintrag hinzufügen und evtl. das DNS Rebind Protection anpassen.
Schau mal hier: https://github.com/s-allius/tsun-gen3-proxy/tree/dev-0.12?tab=readme-ov-file#dns-settings

Leider kenne ich den `AdGuard home` und auch deine Router nicht. Wenn du aber nach DNS Setting und DNS Rebind Protection für deinen Router googelst, solltest du passende Anleitungen finden. Vermutlich ist der `AdGuard Home` dein DNS Server, dann musst du trotzdem das DNS Rebind in deinem Router zulassen, da er feststellt, dass du eine öffentliche Domain auf eine lokale Adresse umgeleitet hast.

**Reply by Hagenncl** [reply]
Hi Stefan, da es leider keine gute Anleitung dazu gibt, habe ich mal eine anleitung geschrieben für den Fall dass man eine Fritz!Box 7490 hat und entsprechend kein direktes DNS rewriting auf der Fritz!Box Oberfläche tätigen kann und damit auf DNS Dienste wie AdGuard zurückgreifen muss um die URL: logger.talent-monitoring.com auf die IP des DNS Servers (HomeAssistant) umzuleiten: 

**DE:**

### **1. AdGuard Home auf Home Assistant installieren**
1. **AdGuard Home installieren**:
   - Öffnen Sie den **Supervisor** in Home Assistant.
   - Gehen Sie zu **Add-on Store** und installieren Sie **AdGuard Home**.
2. **AdGuard Home starten**:
   - Starten Sie das Add-on und öffnen Sie die Weboberfläche (`http://<Home Assistant IP>:3000`).
3. **Konfiguration**:
     - **DNS-Rewrites**:
     - Gehen Sie zu **Settings** > **DNS settings** > **DNS rewrites**.
     - Fügen Sie die Regel hinzu:
       - **Domain name**: `logger.talent-monitoring.com`
       - **IP address**: Die lokale IP-Adresse von Home Assistant, z. B. `192.168.178.50`.

---

### **2. AdGuard Home IP-Adresse ermitteln**
- Notieren Sie sich die lokale IP-Adresse des Geräts, auf dem Home Assistant läuft (z. B. `192.168.178.50`).
- Diese IP wird später in der FRITZ!Box als DNS-Server eingetragen.

---

### **3. DNS-Server in der FRITZ!Box ändern**
1. **FRITZ!Box aufrufen**:
   - Öffnen Sie `http://fritz.box` im Browser und melden Sie sich an.
2. **DNS-Server-Einstellungen ändern**:
   - Gehen Sie zu **Internet** > **Zugangsdaten** > **DNS-Server**.
   - Wählen Sie **Andere DNSv4-Server verwenden**.
   - Tragen Sie die AdGuard-IP ein:
     - **Primärer DNS-Server**: `192.168.178.50` (AdGuard IP).
     - **Sekundärer DNS-Server**: Lassen Sie das Feld leer oder tragen Sie erneut die gleiche IP ein.
   - Speichern Sie die Änderungen.
3. **IPv6-DNS (optional)**:
   - Falls IPv6 genutzt wird, tragen Sie unter **Andere DNSv6-Server verwenden** die IPv6-Adresse von AdGuard ein.

---

### **4. DNS-Rebind-Schutz in der FRITZ!Box konfigurieren**
1. Gehen Sie zu **Heimnetz** > **Netzwerk** > Tab **Netzwerkeinstellungen**.
2. Scrollen Sie nach unten zum Abschnitt **DNS-Rebind-Schutz**.
3. Tragen Sie die Ausnahme ein:
   ```
   logger.talent-monitoring.com
   ```
4. Speichern Sie die Änderungen.

---

### **5. Funktion testen**
1. **DNS-Auflösung testen**:
   - Auf einem Gerät im Netzwerk:
     - Öffnen Sie die Eingabeaufforderung und geben Sie ein:
       ```
       nslookup logger.talent-monitoring.com
       ```
     - Es sollte die IP-Adresse von Home Assistant (z. B. `192.168.178.50`) zurückgegeben werden.
2. **AdGuard Logs prüfen**:
   - Gehen Sie in AdGuard Home zur **Query Log**-Ansicht und prüfen Sie, ob Anfragen an `logger.talent-monitoring.com` auftauchen und korrekt aufgelöst werden.

---

### **Zusammenfassung**
1. Installieren und konfigurieren Sie AdGuard Home auf Home Assistant.
2. Ändern Sie in der FRITZ!Box die DNS-Server auf die IP-Adresse von AdGuard Home.
3. Fügen Sie `logger.talent-monitoring.com` als DNS-Rewrite in AdGuard und als Ausnahme im DNS-Rebind-Schutz der FRITZ!Box hinzu.
4. Testen Sie die Auflösung mit `nslookup` oder den Logs in AdGuard. 

Damit sollte `logger.talent-monitoring.com` korrekt auf die lokale IP von Home Assistant aufgelöst werden.




######################################################################
___________________________________________________________________________________________________________________________
**EN:** 

Here is a concise step-by-step guide to setting up **AdGuard Home** on **Home Assistant** and configuring the **FRITZ!Box 7490** to use AdGuard as the DNS server, including the use of the URL `logger.talent-monitoring.com`:

---

### **1. Install AdGuard Home on Home Assistant**
1. **Install AdGuard Home**:
   - Open **Supervisor** in Home Assistant.
   - Go to the **Add-on Store** and install **AdGuard Home**.
2. **Start AdGuard Home**:
   - Start the add-on and open its web interface (`http://<Home Assistant IP>:3000`).
3. **Configure AdGuard**:
     - **DNS Rewrites**:
     - Navigate to **Settings** > **DNS settings** > **DNS rewrites**.
     - Add the following rewrite:
       - **Domain name**: `logger.talent-monitoring.com`
       - **IP address**: The local IP address of your Home Assistant, e.g., `192.168.178.50`.

---

### **2. Find the AdGuard IP Address**
- Determine the local IP address of the device running Home Assistant (e.g., `192.168.178.50`).
- This IP will be used as the DNS server in the FRITZ!Box configuration.

---

### **3. Configure the FRITZ!Box to Use AdGuard as DNS Server**
1. **Access the FRITZ!Box**:
   - Open `http://fritz.box` in a browser and log in.
2. **Change DNS Server Settings**:
   - Navigate to **Internet** > **Access Data** > **DNS Server**.
   - Select **Use other DNSv4 servers**.
   - Enter the AdGuard IP address:
     - **Primary DNS server**: `192.168.178.50` (AdGuard IP).
     - **Secondary DNS server**: Leave blank or enter the same IP.
   - Save the changes.
3. **IPv6 DNS (Optional)**:
   - If you use IPv6, under **Use other DNSv6 servers**, enter the IPv6 address of AdGuard.

---

### **4. Configure DNS Rebind Protection in the FRITZ!Box**
1. Go to **Home Network** > **Network** > **Network Settings** tab.
2. Scroll down to the **DNS Rebind Protection** section.
3. Add an exception for the domain:
   ```
   logger.talent-monitoring.com
   ```
4. Save the changes.

---

### **5. Test the Configuration**
1. **Test DNS Resolution**:
   - On a device in the network:
     - Open a terminal or command prompt and run:
       ```
       nslookup logger.talent-monitoring.com
       ```
     - The response should return the IP address of Home Assistant (e.g., `192.168.178.50`).
2. **Check AdGuard Logs**:
   - Open AdGuard Home and go to **Query Log**.
   - Verify that queries to `logger.talent-monitoring.com` appear and are resolved correctly.

---

### **Summary**
1. Install and configure AdGuard Home on Home Assistant.
2. Change the DNS server settings in the FRITZ!Box to point to AdGuard Home.
3. Add `logger.talent-monitoring.com` as a DNS rewrite in AdGuard and as an exception in the DNS Rebind Protection settings of the FRITZ!Box.
4. Test the setup with tools like `nslookup` or AdGuard's Query Log.

This configuration ensures that `logger.talent-monitoring.com` resolves correctly to the local IP of Home Assistant.

**Reply by s-allius** [reply]
Danke für die Anleitung. Sobald die aktuelle version released ist, werde ich die ins Wiki hier aufnehmen. Wird vielen helfen...

**Comment by Hagenncl** [comment]
Habe es nun zum laufen bekommen, jedoch nicht so, dass es ohne Einschränkungen nutzbar ist:
1. Hohe Last auf MQTT Broker aufgrund tausender von Nachrichten jede Sekunde
  
![image](https://github.com/user-attachments/assets/c4d19ce0-c547-4342-a5fb-b9253d6a6333)

2. Aktualisierung der Sensordaten in unregelmäßigen Abständen (hauptsächlich nur bei Neustart und dann ewig nicht mehr >15 min)
3.  Keine Verbindung mehr zur TSUN Talent Home App
4.  Regelmäßig Fehlerlogs im Proxy Addon: 

[c676133d_tsun-proxy-dev_2024-12-20T14-22-18.616Z.log](https://github.com/user-attachments/files/18211810/c676133d_tsun-proxy-dev_2024-12-20T14-22-18.616Z.log)



kannst du dir erklären woran das liegt?

**Comment by s-allius** [comment]
Ich habe mir das Log-file mal angeschaut.
- der Inverter baut immer wieder eine neue Verbindung auf, bevor er überhaupt Daten gesendet hat. Das kenne ich nur zur Dämmerung, wenn die PV Module noch nicht genug Energie liefert. Da sehe so 5 -7 Verbindungsaufbauten und dann läuft meist der Inverter sauber durch. Kann also a, Dezember Wetter liegen.
- Die MQTT Nachrichten verstehe ich erstmal nicht. Das sind ja sehr viele Log-Einträge. Sieht nach einer Endlosschleife aus

Evtl. wird die Verbindung statt zu TSUN wieder zum Proxy geleitet und sorgt so für einen neuen Verbindungsaufbau. 

Was passiert den, wenn du `tsun.enabled`auf `false` setzt? Wenn es wirklich ein Schleife ist, dann würde die dadurch unterbrochen

**Reply by s-allius** [reply]
Bitte schau auch mal nach, ob du den AddGuard richtig aufgesetzt hast. Insbesondere der 1. Punkt aus der Installation hier: https://community.home-assistant.io/t/home-assistant-community-add-on-adguard-home/90684

Ist wichtig:
Ensure your Home Assistant device has a static IP and static [external DNS servers! ](https://github.com/home-assistant/hassos/blob/dev/Documentation/network.md#static-ip)`

Hier muss der DNS Eintrag auf einen öffentlichen DNS Server zeigen (z.B. 8.8.8.8 und 4.4.4.4) und darf nicht auf die Fritz!Box zeigen!

**Reply by s-allius** [reply]
Ich habe mal eine Erkennung für das Problem, in den Proxy eingebaut. Wenn du as AddOn in der dev Variante aktualisierst, sollte nun eine bessere Fehlermeldung im Log kommen und die Loop automatisch unterbrochen werden.

**Reply by Hagenncl** [reply]
Hi Stefan, du hattest recht, ich war in einer Dauerschleife gefangen , was am Ende auch meinen Raspberry so in die höhe steigen lassen hat. 
Statische IP hatte ich bereits. Jedoch hatte der HomeAssistant wieder zurück auf die Fritz!Box gerootet. 
Habe mal wieder anbei eine Anleitung für die Variante Core und Supervised auf DE und EN geschrieben: 



**Deutsch:** 
**Home Assistant OS (Supervisor) - DNS-Server einstellen**
Schritte:
1.	Öffne das Webinterface:
        o	Rufe die Benutzeroberfläche von Home Assistant über deinen Browser auf (z. B. http://homeassistant.local:8123).
2.	Gehe zu den Einstellungen:
         o	Navigiere zu Einstellungen > System > Netzwerk.
3.	Netzwerkschnittstelle auswählen:
        o	Klicke auf die aktive Netzwerkschnittstelle (z. B. eth0 für kabelgebundene Verbindungen oder wlan0 für WLAN).
4.	DNS-Server konfigurieren:
        o	Scrolle nach unten zum Abschnitt für DNS-Server.
        o	Lösche zunächst die IP-Adresse, die auf die FRITZ!Box zeigt (z. B. 192.168.178.1), da diese den DNS-Traffic über die FRITZ!Box leiten würde.
         o	Wähle anschließend im Dropdown-Menü die Option Google (8.8.8.8, 8.8.4.4) aus.
5.	Speichern und Neustarten:
        o	Speichere die Änderungen.
        o	Starte Home Assistant neu, damit die neuen DNS-Einstellungen übernommen werden.
6.	Überprüfung:
        o	Teste, ob die DNS-Einstellungen funktionieren, indem du sicherstellst, dass Home Assistant externe Webseiten oder Dienste wie Updates erreichen kann.
________________________________________
**English:** 
**Home Assistant OS (Supervisor) - Configure DNS Servers**
Steps:
1.	Open the Web Interface:
        o	Access the Home Assistant interface via your browser (e.g., http://homeassistant.local:8123).
2.	Go to Settings:
        o	Navigate to Settings > System > Network.
3.	Select the Network Interface:
        o	Click on the active network interface (e.g., eth0 for wired connections or wlan0 for Wi-Fi).
4.	Configure DNS Servers:
        o	Scroll down to the DNS server section.
        o	First, delete the IP address pointing to the FRITZ!Box (e.g., 192.168.178.1), as it would route DNS traffic through the FRITZ!Box.
        o	Then, from the dropdown menu, select the option Google (8.8.8.8, 8.8.4.4).
5.	Save and Restart:
        o	Save the changes.
        o	Restart Home Assistant to apply the new DNS settings.
6.	Verification:
        o	Verify that the DNS settings are working by ensuring Home Assistant can access external websites or services like updates.

**Reply by Hagenncl** [reply]
Aktuell ist der Polling Intervall 5 min. Kann ich den z.B. auf 30 sekunden umstellen oder ist das vom Microwechselrichter vorgegeben?

**Reply by s-allius** [reply]
Die 5 Minuten werden vom Wechselrichter vorgegeben. Aber der Proxy kann im Polling Modus auch selbst die Werte abfrage, das ist aktuell auf 30 Sekunden eingestellt. Dazu setzt du in der Konfiguration `modbus_polling` auf true.

**Reply by Hagenncl** [reply]
Perfekt , das mach ich , danke dir für den Support :) und super mit dem addon (y)

**Comment by Hagenncl** [comment]
Zusätzlich noch die Entitäten als Sensoren in der Configuration.yaml eingebunden, damit sie als Sensoren im Energiedashbaord und für weitere Entitäten genutzt werden können: 

```
template:
  - sensor:
    # TSUN Wechselrichter tägliche Produktion
      - name: "TSUN Wechselrichter tägliche Produktion"
        unique_id: "TSUN Wechselrichter tägliche Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.micro_inverter_daily_generation')) | round(2) }}
  - sensor:
    # TSUN Wechselrichter gesamte Produktion
      - name: "TSUN Wechselrichter gesamte Produktion"
        unique_id: "TSUN Wechselrichter gesamte Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.micro_inverter_total_generation')) | round(2) }}
  - sensor:
    # TSUN Wechselrichter aktuelle Leistung
      - name: "TSUN Wechselrichter aktuelle Leistung"
        unique_id: "TSUN Wechselrichter aktuelle Leistung"
        unit_of_measurement: 'W'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.micro_inverter_power')) | round(2) }}
  - sensor:
    # TSUN Modul 1 tägliche Produktion
      - name: "TSUN Modul 1 tägliche Produktion"
        unique_id: "TSUN Modul 1 tägliche Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv1_daily_generation')) | round(2) }}
  - sensor:
    # TSUN Modul 1 gesamte Produktion
      - name: "TSUN Modul 1 gesamte Produktion"
        unique_id: "TSUN Modul 1 gesamte Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv1_total_generation')) | round(2) }}
  - sensor:
    # TSUN Modul 1 aktuelle Leistung
      - name: "TSUN Modul 1 aktuelle Leistung"
        unique_id: "TSUN Modul 1 aktuelle Leistung"
        unit_of_measurement: 'W'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv1_power')) | round(2) }}
  - sensor:
    # TSUN Modul 2 tägliche Produktion
      - name: "TSUN Modul 2 tägliche Produktion"
        unique_id: "TSUN Modul 2 tägliche Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv2_daily_generation')) | round(2) }}
  - sensor:
    # TSUN Modul 2gesamte Produktion
      - name: "TSUN Modul 2 gesamte Produktion"
        unique_id: "TSUN Modul 2 gesamte Produktion"
        unit_of_measurement: 'kWh'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv2_total_generation')) | round(2) }}
  - sensor:
    # TSUN Modul 2 aktuelle Leistung
      - name: "TSUN Modul 2 aktuelle Leistung"
        unique_id: "TSUN Modul 2 aktuelle Leistung"
        unit_of_measurement: 'W'
        device_class: "energy"
        state_class: "total_increasing"
        state: >-
            {{ float(states('sensor.module_pv2_power')) | round(2) }}
```
