### ISSUE TITLE
GEN3PLUS: Add support for port 8899

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#117]
With the latest firmware update, TSUN has introduced encryption for the connection of the inverter to the TSUN server. This means that the "man in the middle" approach for proxy setup no longer works.

The GEN3PLUS inverters can receive commands and return measured values via port 8899. This connection is not encrypted and should be used to read the measured values from SSL inverters as well.

**Comment by s-allius** [comment]
fixed by #118 

to establish a connection from the proxy to your inverter you must add one config line to your `config.toml` file. Look at the example )line `client_mode` and adapt the IP address of your inverter.
```toml
[inverters."Y170000000000001"]
monitor_sn = 2000000000       # The "Monitoring SN:" can be found on a sticker enclosed with the inverter
#node_id = ''                 # Optional, MQTT replacement for inverters serial number  
#suggested_area = ''          # Optional, suggested installation place for home-assistant
client_mode = {host = '192.168.0.1', port = 8899}
```
It is important that your inverter has a fixed IP address or your DHCP server approve always the same IP to your inverter (DHCP Feature fixed lease). If your inverter is in a different network you must also add a route to your router. Otherwise the proxy can't establish a connection
