### ISSUE TITLE
Extent the configuration for Smart Meter and Batteries

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#285]
To support devices other than inverters, we have several approaches. At the moment, the configuration in config.toml always starts with the keyword `inverters`. Now we can:
1. simply add the new device types under `inverters` as well. Disadvantage, we do not check the grammar for the individual devices, as this depends on the data entered (e.g. serial number)
2. add separate keywords like, `smart_meters`, `batteries`. Then we could customize the grammar for each type specifically.

I would prefer the second approach.

@mime24 : What do you think? How can we map this for the add-on?

Example:
```toml
[inverters."R170000000000001"]  # must start with R17, Y17 or Y47
node_id = 'inv1'                 # MQTT replacement for inverters serial number  
suggested_area = 'Roof'  # suggested installation place for home-assistant

[batteries."4100000000000001"]  # must start with 410
monitor_sn = 2070233888
node_id = 'batt1'                    # MQTT replacement for battery serial number  
suggested_area = 'Garage'  # suggested installation place for home-assistant
```
